/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RobotSimulatorJni */

#ifndef _Included_RobotSimulatorJni
#define _Included_RobotSimulatorJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RobotSimulatorJni
 * Method:    createRobot
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_RobotSimulatorJni_createRobot
  (JNIEnv *, jclass);

/*
 * Class:     RobotSimulatorJni
 * Method:    startCompetition
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_RobotSimulatorJni_startCompetition
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
